"""Generate real analytic A3 whiteprints with CYBR GEO's drawing pipeline.

Load only the trusted assembly.pkl generated by this recipe's build command.
"""
from pathlib import Path
import argparse,sys,pickle,json
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'src'));sys.path.insert(0,str(Path(__file__).resolve().parent))
from recipe import coupled_pose
from mechanism_lab.whiteprint import whiteprint

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--out',type=Path,default=ROOT/'build/aeris');args=ap.parse_args()
    with (args.out/'assembly.pkl').open('rb') as f:a=pickle.load(f)
    a.motion_function=coupled_pose;folder=args.out/'whiteprints';folder.mkdir(exist_ok=True)
    sets={
      'capture_hood':(['Asymmetric_hollow_capture_hood','Hood_mating_collar'],'AERIS / HOLLOW CAPTURE HOOD'),
      'impeller':([p.name for p in a.parts if p.group=='impeller'],'AERIS / LOFTED IMPELLER ASSEMBLY'),
      'volute':(['Spiral_volute_hollow_casting'],'AERIS / HOLLOW SPIRAL VOLUTE')
    }
    for name,(parts,title) in sets.items():
        print('WHITEPRINT_START',name,flush=True)
        r=whiteprint(a,folder/name,part_names=parts,title=title)
        assert r['method']=='OCP analytic hidden-line removal'
        print('WHITEPRINT_DONE',name,flush=True)

if __name__=='__main__':main()
