"""Package verified original procedural face renders and their linear masters."""
from __future__ import annotations
import argparse
import hashlib
import importlib.metadata
import json
from pathlib import Path
import shutil
import sys
import zipfile
import numpy as np
from PIL import Image
import mitsuba as mi

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tools'))
import orbit_mitsuba_photo as v9
from render_procedural_face import save_png_atomic


def package(source,out):
    out.mkdir(parents=True,exist_ok=True)
    (out/'linear_masters').mkdir(exist_ok=True)
    names=[];reports=[]
    for view in ['portrait','profile','portrait_clay']:
        stem='CYBR_Procedural_Face_'+view
        report=json.loads((source/(stem+'.json')).read_text())
        provenance=report['source']
        if provenance['scan_used'] or provenance['photographic_skin_textures'] or provenance['imported_anatomy_mesh']:
            raise ValueError('A nonprocedural anatomical input cannot be packaged as original')
        beauty=v9.read_pfm(source/(stem+'_beauty.pfm'))
        filtered=v9.read_pfm(source/(stem+'_denoised.pfm'))
        if not np.isfinite(beauty).all() or not np.isfinite(filtered).all() or beauty.mean()<1e-5:
            raise ValueError('Invalid or blank linear master')
        target='CYBR_Face_'+view
        for suffix,linear in [('',filtered),('_raw',beauty)]:
            name=target+suffix+'.png';save_png_atomic(linear,out/name,report['exposure_multiplier'])
            with Image.open(out/name) as im:
                im.load()
                assert list(im.size)==report['resolution']
                if not suffix:
                    assert hashlib.sha256(np.asarray(im).tobytes()).hexdigest()==report['png_pixels_sha256']
            names.append(name)
            exr='linear_masters/'+target+('_denoised' if not suffix else '_beauty')+'_linear.exr'
            mi.Bitmap(np.ascontiguousarray(linear)).write(str(out/exr));names.append(exr)
        report['delivered_image']=target+'.png';reports.append(report)
    model=source/'CYBR_Procedural_Human_Face.glb'
    if hashlib.sha256(model.read_bytes()).hexdigest()!=reports[0]['model_sha256']:
        raise ValueError('The packaged model differs from the portrait render receipt')
    shutil.copy2(model,out/'CYBR_Human_Face.glb')
    names.append('CYBR_Human_Face.glb')
    (out/'render_evidence.json').write_text(json.dumps(reports,indent=2)+'\n');names.append('render_evidence.json')
    (out/'procedural_parameters.json').write_text(json.dumps(reports[0]['source']['parameters'],indent=2)+'\n')
    names.append('procedural_parameters.json')
    shutil.copy2(source/'texture_provenance.json',out/'texture_provenance.json');names.append('texture_provenance.json')
    shutil.copy2(ROOT/'docs/procedural_face_validation.json',out/'geometry_validation.json')
    names.append('geometry_validation.json')
    environment={name:importlib.metadata.version(name) for name in ['numpy','scipy','trimesh','Pillow','mitsuba','drjit']}
    (out/'render_environment.json').write_text(json.dumps(environment,indent=2)+'\n');names.append('render_environment.json')
    (out/'README.txt').write_text(
        'CYBR GEO / ORIGINAL PROCEDURAL HUMAN FACE / V9\n\n'
        'This delivery replaces the previous scan-based portrait.\n'
        'No input scans, anatomy meshes, photographs, texture libraries or learned face models.\n'
        'All anatomical surfaces, pigment fields, pores and individual hair shafts are generated by code.\n'
        'The studio contains modeled area lights and an analytic constant fill; no HDR image is used.\n\n'
        'Portrait: 1440 x 1800, 512 spp. Profile: 1200 x 1500, 384 spp.\n'
        'Clay: 960 x 1200, 128 spp. Maximum path depth: 14.\n'
        'Actual Mitsuba LLVM CPU path tracing, physical thin lens, v9 Gaussian filter,\n'
        'linear beauty/albedo/world-normal AOVs, Intel OIDN, original v9 tone mapping.\n\n'
        'GEOMETRY AND MATERIAL LIMITS\n'
        'Original artistic anatomy, not a measured or medically validated person.\n'
        'Skin scattering uses a surface BSDF approximation rather than multilayer tissue transport.\n'
        'The glTF assembly has hidden overlapping surfaces and is not a watertight print.\n'
        'GLB coordinates: metres, Y up. Color maps are embedded. Offline pore-height shading\n'
        'and refractive ocular materials are reproduced by the dedicated renderer.\n\n'
        'FILES\n'
        'PNG: final images and raw comparisons. linear_masters/: float EXR masters.\n'
        'JSON: exact render evidence, procedural parameters, texture hashes and validation.\n'
        'CYBR_Human_Face.glb: the actual render assembly.\n\n'
        'SOURCE / GPL-2.0\n'
        'https://github.com/cybrdelic/cybr-geo/tree/feat/procedural-human-face-v9\n'
        'See docs/HUMAN_FACE.md, examples/procedural_human_face.py and tools/render_human_face.py.\n')
    names.append('README.txt')
    archive=out/'CYBR_Face_Render_Package.zip'
    with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED,compresslevel=5) as z:
        for name in sorted(names):z.write(out/name,name)
    with zipfile.ZipFile(archive) as z:
        if set(z.namelist())!=set(names) or z.testzip():raise ValueError('Invalid render archive')
    return {'archive':str(archive),'members':len(names),'bytes':archive.stat().st_size,
            'image_pixel_hashes_verified':True,'scan_inputs':False}


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--input',type=Path,default=ROOT/'build/procedural_face_final')
    p.add_argument('--out',type=Path,required=True);args=p.parse_args()
    print(json.dumps(package(args.input.resolve(),args.out.resolve()),indent=2))


if __name__=='__main__':main()
